# -*- coding: utf-8 -*-
"""Logistic_Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13GPhfS0vHC0x7CZGvQE6DlNpkCCd-nvE
"""

import numpy as np
import pandas as pd

dataframe = pd.read_csv('ionosphere.csv')

dataframe

dataframe['Actual_Class'] = np.where(dataframe['Class'] == 'good', 0, 1)

dataframe

dataframe = dataframe.drop(columns = ['Class'])

dataframe

y = dataframe['Actual_Class']
X = dataframe.drop(columns = ['Actual_Class'])

X

y

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression(random_state=0)
classifier.fit(X_train, y_train)

X_test_pred = classifier.predict(X_test)

X_test_pred

from sklearn.metrics import accuracy_score

accuracy = np.around(accuracy_score(X_test_pred, y_test)*100, 2)
print(accuracy)

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

cm = confusion_matrix(y_test, X_test_pred)
disp = ConfusionMatrixDisplay(confusion_matrix = cm)
disp.plot()